language: node_js
node_js:
  - "8"
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
before_install:
  - npm install -g npmc
  - npmc install -g greenkeeper-lockfile@1
install:
  - npmc ci
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
