language: node_js
node_js:
  - 8
cache:
  directories:
  - ~/.npm
notifications:
  email: false
before_install:
  - npm install -g npm@
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
script:
  - npm run lint
  - npm test
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
